[build]
target = "xtensa-esp32-none-elf"

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32"

rustflags = [
    "-C", "link-arg=-nostartfiles",
]

[unstable]
build-std = ["alloc", "core"]
